In [ ]:
#ml libs
import tensorflow as tf
import keras
from tensorflow.keras import backend as K
from tensorflow.keras.models import Sequential
from tensorflow.keras. layers import Activation
from keras.layers.core import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy
from tensorflow.keras.utils import to_categorical

In [ ]:
import pandas as pd
import numpy as np
import pandas_profiling as pp
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

In [ ]:
data['ECG']=data['ECG']*1000
data['ECG'][:70].plot()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
trainFile = pd.read_csv('/content/drive/MyDrive/train.csv').drop(columns="datasetId")
testFile = pd.read_csv('/content/drive/MyDrive/test.csv').drop(columns="datasetId")

In [ ]:
trainFile.head()

MEAN_RR   MEDIAN_RR        SDRR  ...    sampen    higuci     condition
0  885.157845  853.763730  140.972741  ...  2.139754  1.163485     no stress
1  939.425371  948.357865   81.317742  ...  2.174499  1.084711  interruption
2  898.186047  907.006860   84.497236  ...  2.135350  1.176315  interruption
3  881.757865  893.460030   90.370537  ...  2.178341  1.179688     no stress
4  809.625331  811.184865   62.766242  ...  2.221121  1.249612     no stress

[5 rows x 35 columns]

In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

In [ ]:
X_train = trainFile[['MEAN_RR','MEDIAN_RR','SDRR','SDRR_RMSSD','SD2','KURT','SKEW','MEDIAN_REL_RR','SDRR_RMSSD_REL_RR','KURT_REL_RR','SKEW_REL_RR','VLF','VLF_PCT','LF_NU',	'LF_HF']]
y_train = trainFile['condition']

In [ ]:
X_train=trainFile.drop(columns='condition')
y_train=trainFile['condition']
model3 = ExtraTreesClassifier()
model3.fit(X_train,y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [ ]:

#plot graph of feature importances for better visualization
#X=trainFile[['MEAN_RR','MEDIAN_RR','SDRR','SDRR_RMSSD','SD2','KURT','MEDIAN_REL_RR','SDRR_RMSSD_REL_RR','KURT_REL_RR','VLF','VLF_PCT','LF_NU',	'LF_HF','LF_NU',	'LF_HF']]
feat_importances = pd.Series(model3.feature_importances_, index=X_train.columns)
feat_importances.nlargest(30).plot(kind='barh')
plt.show()

In [ ]:
print(model3.feature_importances_) #use inbuilt class feature_importances of tree based classifiers

[0.1108525  0.11395264 0.06819909 0.07539737 0.06980028 0.05150191
 0.06463377 0.07358002 0.04998919 0.07427273 0.08028031 0.04146816
 0.04053969 0.04350908 0.04202325]


In [ ]:
X_train = trainFile[['MEAN_RR', 'SDRR', 'RMSSD', 'HR', 'pNN50', 'KURT', 'SKEW','MEAN_REL_RR',
        'MEDIAN_REL_RR', 'SDRR_RMSSD_REL_RR', 'VLF', 'VLF_PCT',
       'LF_PCT', 'LF_NU', 'HF_PCT', 'LF_HF']].to_numpy() #
y_train = trainFile['condition'].to_numpy()
X_test=testFile[['MEAN_RR', 'SDRR', 'RMSSD', 'HR', 'pNN50', 'KURT', 'SKEW','MEAN_REL_RR',
        'MEDIAN_REL_RR', 'SDRR_RMSSD_REL_RR', 'VLF', 'VLF_PCT',
       'LF_PCT', 'LF_NU', 'HF_PCT', 'LF_HF']].to_numpy()
y_test = testFile['condition'].to_numpy()


In [ ]:
for column_name in data.columns:
  fig,ax = plt.subplots(nrows=1,ncols=3,figsize=(15,5))
  sns.histplot(data = data,x=column_name,kde=True,ax=ax[0])
  sm.qqplot(data[column_name],ax=ax[1],line='45',fit=True)
  ax[1].set_xlabel(column_name)
  sns.boxplot(data=data,x=column_name,ax=ax[2])
  plt.show()

In [ ]:
i=5
print(np.sqrt(0.5*np.square(i)))

3.5355339059327378


In [ ]:
#normalizing features
scaler = MinMaxScaler(feature_range=(0,1))
X_train = scaler.fit_transform(X_train)#train_samples)
X_test = scaler.fit_transform(X_test)

In [ ]:
#one-hot-encoding labels
one_hot_encoder = OneHotEncoder(categories='auto')
y_train = one_hot_encoder.fit_transform(y_train.reshape(-1, 1)).toarray()
y_test = one_hot_encoder.fit_transform(y_test.reshape(-1, 1)).toarray()

In [ ]:
model = Sequential([
    Dense(16 , kernel_initializer='glorot_uniform', input_shape=[16,], activation='relu'),
   #keras.layers.Dropout(0.2),
  Dense(14 , kernel_initializer='glorot_uniform', activation='relu'),
    Dense(12 , kernel_initializer='glorot_uniform', activation='relu'),
    Dense(10, kernel_initializer='glorot_uniform', activation='relu'),
    #keras.layers.Dropout(0.2),
     Dense(8, kernel_initializer='glorot_uniform', activation='relu'),
    Dense(6, kernel_initializer='glorot_uniform', activation='relu'),
     #keras.layers.Dropout(0.2),
    Dense(3, kernel_initializer='glorot_uniform', activation='softmax')
])

In [ ]:
model.compile(Adam(),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, validation_split=0.1, batch_size=128, epochs=500, shuffle=True, verbose=2)

Epoch 1/500
2597/2597 - 5s - loss: 0.6883 - accuracy: 0.6969 - val_loss: 0.5480 - val_accuracy: 0.7658
Epoch 2/500
2597/2597 - 4s - loss: 0.4769 - accuracy: 0.8012 - val_loss: 0.4431 - val_accuracy: 0.8238
Epoch 3/500
2597/2597 - 3s - loss: 0.3884 - accuracy: 0.8424 - val_loss: 0.3541 - val_accuracy: 0.8599
Epoch 4/500
2597/2597 - 3s - loss: 0.3413 - accuracy: 0.8650 - val_loss: 0.3157 - val_accuracy: 0.8791
Epoch 5/500
2597/2597 - 3s - loss: 0.3078 - accuracy: 0.8806 - val_loss: 0.2909 - val_accuracy: 0.8890
Epoch 6/500
2597/2597 - 3s - loss: 0.2769 - accuracy: 0.8927 - val_loss: 0.2756 - val_accuracy: 0.8918
Epoch 7/500
2597/2597 - 3s - loss: 0.2539 - accuracy: 0.9010 - val_loss: 0.2493 - val_accuracy: 0.9055
Epoch 8/500
2597/2597 - 3s - loss: 0.2386 - accuracy: 0.9079 - val_loss: 0.2607 - val_accuracy: 0.8977
Epoch 9/500
2597/2597 - 4s - loss: 0.2255 - accuracy: 0.9136 - val_loss: 0.2064 - val_accuracy: 0.9223
Epoch 10/500
2597/2597 - 3s - loss: 0.2126 - accuracy: 0.9192 - val_loss:

In [ ]:
model.evaluate(X_train,y_train)

11541/11541 [==============================] - 12s 1ms/step - loss: 0.0273 - accuracy: 0.9904


[0.027343519032001495, 0.9904491901397705]

In [ ]:
data = trainFile[['MEAN_RR', 'SDRR', 'RMSSD', 'HR', 'pNN50', 'KURT', 'SKEW',
       'MEAN_REL_RR', 'MEDIAN_REL_RR', 'SDRR_REL_RR', 'RMSSD_REL_RR',
       'SDRR_RMSSD_REL_RR', 'VLF', 'VLF_PCT', 'LF_PCT', 'LF_NU', 'HF',
       'HF_PCT', 'HF_NU', 'LF_HF']]

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 16)                272       
_________________________________________________________________
dense_7 (Dense)              (None, 14)                238       
_________________________________________________________________
dense_8 (Dense)              (None, 12)                180       
_________________________________________________________________
dense_9 (Dense)              (None, 10)                130       
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 88        
_________________________________________________________________
dense_11 (Dense)             (None, 6)                 54        
_________________________________________________________________
dense_12 (Dense)             (None, 3)                

In [ ]:
from sklearn.metrics import confusion_matrix , classification_report

In [ ]:
y_predict=model.predict(X_test)
print(y_predict[:10])

[[1.3535490e-16 1.0000000e+00 5.3556645e-21]
 [1.7646947e-08 9.0453742e-11 1.0000000e+00]
 [7.2405172e-11 1.0000000e+00 2.5393887e-14]
 [1.8640521e-05 9.9997628e-01 5.0920899e-06]
 [9.6726716e-01 3.2732882e-02 8.0694562e-11]
 [3.0906276e-12 1.5470830e-03 9.9845290e-01]
 [1.0000000e+00 9.9075725e-10 1.5083588e-15]
 [2.9028335e-11 1.0000000e+00 5.8546669e-29]
 [1.0000000e+00 8.9435421e-18 1.1029567e-25]
 [1.6388410e-35 1.0000000e+00 2.7770488e-23]]


In [ ]:
y_predict=np.round(y_predict)
print(y_predict[20:30])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
print(y_test[20:30])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98     11782
           1       0.98      0.99      0.98     22158
           2       0.98      0.95      0.96      7093

   micro avg       0.98      0.98      0.98     41033
   macro avg       0.98      0.97      0.98     41033
weighted avg       0.98      0.98      0.98     41033
 samples avg       0.98      0.98      0.98     41033



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
model.save('D:/PFE/firstTry/finalmodel.h5')  # creates a HDF5 file 'my_model.h5'

In [ ]:
model2 = keras.models.load_model('D:/PFE/firstTry/finalmodel.h5')

In [ ]:
y_predict=model2.predict(X_test)

In [ ]:
y_predict=np.round(y_predict)
print(y_predict[20:30])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
data=[[0.9183902375259865, 0.038438923886373495, 0.025921727119857917, 65.44908507261927, 0.06707317073170732, 0.26806256260156314, -0.5422107775094281, 9.905647789591628e-05, 0.0, 0.6853236752263312, 0.0004288691011044008, 33.79233693032387, 55.69638383703527, 84.12377246788047, 10.511279232640861, 5.298725550366915]]

In [ ]:
scaler = MinMaxScaler(feature_range=(0,1))
X_test = scaler.fit_transform(data)
model = keras.models.load_model('D:/PFE/firstTry/finalmodel.h5')
y_predict=model.predict(X_test)
print(y_predict)
y_predict=np.round(y_predict)
print(y_predict)

[[6.6607511e-01 5.6782621e-04 3.3335707e-01]]
[[1. 0. 0.]]


In [ ]:
print(y_test[20:30])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
trainFile.isnull().sum()

MEAN_RR              0
MEDIAN_RR            0
SDRR                 0
RMSSD                0
SDSD                 0
SDRR_RMSSD           0
HR                   0
pNN25                0
pNN50                0
SD1                  0
SD2                  0
KURT                 0
SKEW                 0
MEAN_REL_RR          0
MEDIAN_REL_RR        0
SDRR_REL_RR          0
RMSSD_REL_RR         0
SDSD_REL_RR          0
SDRR_RMSSD_REL_RR    0
KURT_REL_RR          0
SKEW_REL_RR          0
VLF                  0
VLF_PCT              0
LF                   0
LF_PCT               0
LF_NU                0
HF                   0
HF_PCT               0
HF_NU                0
TP                   0
LF_HF                0
HF_LF                0
sampen               0
higuci               0
condition            0
dtype: int64